[workspace]
resolver = "2"
members = ["crates/core", "crates/cli", "crates/metrics", "crates/wasm"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/bem1r0d1/png2svg"

[profile.release]
lto = true
codegen-units = 1

[profile.release.package.png2svg-wasm]
opt-level = "z"
